/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/cloud/dialogflow/v2beta1/agent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "agent.pb-c.h"
void   google__cloud__dialogflow__v2beta1__agent__init
                     (Google__Cloud__Dialogflow__V2beta1__Agent         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__Agent init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__agent__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__Agent *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__agent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__agent__pack
                     (const Google__Cloud__Dialogflow__V2beta1__Agent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__agent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__agent__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__Agent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__agent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__Agent *
       google__cloud__dialogflow__v2beta1__agent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__Agent *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__agent__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__agent__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__Agent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__agent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__get_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__GetAgentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__GET_AGENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__get_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_agent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__get_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_agent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__get_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_agent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *
       google__cloud__dialogflow__v2beta1__get_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__get_agent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__get_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_agent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__search_agents_request__init
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__SEARCH_AGENTS_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__search_agents_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__search_agents_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__search_agents_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *
       google__cloud__dialogflow__v2beta1__search_agents_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__search_agents_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__search_agents_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__search_agents_response__init
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__SEARCH_AGENTS_RESPONSE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__search_agents_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__search_agents_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__search_agents_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *
       google__cloud__dialogflow__v2beta1__search_agents_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__search_agents_response__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__search_agents_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__search_agents_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__train_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__TRAIN_AGENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__train_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__train_agent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__train_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__train_agent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__train_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__train_agent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *
       google__cloud__dialogflow__v2beta1__train_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__train_agent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__train_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__train_agent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__export_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__export_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__export_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__export_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *
       google__cloud__dialogflow__v2beta1__export_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__export_agent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__export_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__export_agent_response__init
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__export_agent_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__export_agent_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__export_agent_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *
       google__cloud__dialogflow__v2beta1__export_agent_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__export_agent_response__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__export_agent_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__export_agent_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__import_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__import_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__import_agent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__import_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__import_agent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__import_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__import_agent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *
       google__cloud__dialogflow__v2beta1__import_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__import_agent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__import_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__import_agent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__restore_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *
       google__cloud__dialogflow__v2beta1__restore_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__restore_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue google__cloud__dialogflow__v2beta1__agent__match_mode__enum_values_by_number[3] =
{
  { "MATCH_MODE_UNSPECIFIED", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_UNSPECIFIED", 0 },
  { "MATCH_MODE_HYBRID", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_HYBRID", 1 },
  { "MATCH_MODE_ML_ONLY", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_ML_ONLY", 2 },
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__agent__match_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex google__cloud__dialogflow__v2beta1__agent__match_mode__enum_values_by_name[3] =
{
  { "MATCH_MODE_HYBRID", 1 },
  { "MATCH_MODE_ML_ONLY", 2 },
  { "MATCH_MODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor google__cloud__dialogflow__v2beta1__agent__match_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.Agent.MatchMode",
  "MatchMode",
  "Google__Cloud__Dialogflow__V2beta1__Agent__MatchMode",
  "google.cloud.dialogflow.v2beta1",
  3,
  google__cloud__dialogflow__v2beta1__agent__match_mode__enum_values_by_number,
  3,
  google__cloud__dialogflow__v2beta1__agent__match_mode__enum_values_by_name,
  1,
  google__cloud__dialogflow__v2beta1__agent__match_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__agent__field_descriptors[10] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, default_language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supported_language_codes",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, n_supported_language_codes),
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, supported_language_codes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_zone",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, time_zone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar_uri",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, avatar_uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_logging",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, enable_logging),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_mode",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, match_mode),
    &google__cloud__dialogflow__v2beta1__agent__match_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classification_threshold",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__Agent, classification_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__agent__field_indices_by_name[] = {
  6,   /* field[6] = avatar_uri */
  9,   /* field[9] = classification_threshold */
  2,   /* field[2] = default_language_code */
  5,   /* field[5] = description */
  1,   /* field[1] = display_name */
  7,   /* field[7] = enable_logging */
  8,   /* field[8] = match_mode */
  0,   /* field[0] = parent */
  3,   /* field[3] = supported_language_codes */
  4,   /* field[4] = time_zone */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__agent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__agent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.Agent",
  "Agent",
  "Google__Cloud__Dialogflow__V2beta1__Agent",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__Agent),
  10,
  google__cloud__dialogflow__v2beta1__agent__field_descriptors,
  google__cloud__dialogflow__v2beta1__agent__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__agent__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__agent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__get_agent_request__field_descriptors[1] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__GetAgentRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__get_agent_request__field_indices_by_name[] = {
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__get_agent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__get_agent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.GetAgentRequest",
  "GetAgentRequest",
  "Google__Cloud__Dialogflow__V2beta1__GetAgentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__GetAgentRequest),
  1,
  google__cloud__dialogflow__v2beta1__get_agent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__get_agent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__get_agent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__get_agent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__search_agents_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest, page_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_token",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest, page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__search_agents_request__field_indices_by_name[] = {
  1,   /* field[1] = page_size */
  2,   /* field[2] = page_token */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__search_agents_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__search_agents_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.SearchAgentsRequest",
  "SearchAgentsRequest",
  "Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest),
  3,
  google__cloud__dialogflow__v2beta1__search_agents_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__search_agents_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__search_agents_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__search_agents_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__search_agents_response__field_descriptors[2] =
{
  {
    "agents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse, n_agents),
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse, agents),
    &google__cloud__dialogflow__v2beta1__agent__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_page_token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse, next_page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__search_agents_response__field_indices_by_name[] = {
  0,   /* field[0] = agents */
  1,   /* field[1] = next_page_token */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__search_agents_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__search_agents_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.SearchAgentsResponse",
  "SearchAgentsResponse",
  "Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse),
  2,
  google__cloud__dialogflow__v2beta1__search_agents_response__field_descriptors,
  google__cloud__dialogflow__v2beta1__search_agents_response__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__search_agents_response__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__search_agents_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__train_agent_request__field_descriptors[1] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__train_agent_request__field_indices_by_name[] = {
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__train_agent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__train_agent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.TrainAgentRequest",
  "TrainAgentRequest",
  "Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest),
  1,
  google__cloud__dialogflow__v2beta1__train_agent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__train_agent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__train_agent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__train_agent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__export_agent_request__field_descriptors[2] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_uri",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest, agent_uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__export_agent_request__field_indices_by_name[] = {
  1,   /* field[1] = agent_uri */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__export_agent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__export_agent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.ExportAgentRequest",
  "ExportAgentRequest",
  "Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest),
  2,
  google__cloud__dialogflow__v2beta1__export_agent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__export_agent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__export_agent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__export_agent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__export_agent_response__field_descriptors[2] =
{
  {
    "agent_uri",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse, agent_uri),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_content",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse, agent_content),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__export_agent_response__field_indices_by_name[] = {
  1,   /* field[1] = agent_content */
  0,   /* field[0] = agent_uri */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__export_agent_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__export_agent_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.ExportAgentResponse",
  "ExportAgentResponse",
  "Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse),
  2,
  google__cloud__dialogflow__v2beta1__export_agent_response__field_descriptors,
  google__cloud__dialogflow__v2beta1__export_agent_response__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__export_agent_response__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__export_agent_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__import_agent_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_uri",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest, agent_uri),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_content",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest, agent_content),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__import_agent_request__field_indices_by_name[] = {
  2,   /* field[2] = agent_content */
  1,   /* field[1] = agent_uri */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__import_agent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__import_agent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.ImportAgentRequest",
  "ImportAgentRequest",
  "Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest),
  3,
  google__cloud__dialogflow__v2beta1__import_agent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__import_agent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__import_agent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__import_agent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__restore_agent_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_uri",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest, agent_uri),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "agent_content",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest, agent_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest, agent_content),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__restore_agent_request__field_indices_by_name[] = {
  2,   /* field[2] = agent_content */
  1,   /* field[1] = agent_uri */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__restore_agent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.RestoreAgentRequest",
  "RestoreAgentRequest",
  "Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest),
  3,
  google__cloud__dialogflow__v2beta1__restore_agent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__restore_agent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__restore_agent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__restore_agent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor google__cloud__dialogflow__v2beta1__agents__method_descriptors[6] =
{
  { "GetAgent", &google__cloud__dialogflow__v2beta1__get_agent_request__descriptor, &google__cloud__dialogflow__v2beta1__agent__descriptor },
  { "SearchAgents", &google__cloud__dialogflow__v2beta1__search_agents_request__descriptor, &google__cloud__dialogflow__v2beta1__search_agents_response__descriptor },
  { "TrainAgent", &google__cloud__dialogflow__v2beta1__train_agent_request__descriptor, &google__longrunning__operation__descriptor },
  { "ExportAgent", &google__cloud__dialogflow__v2beta1__export_agent_request__descriptor, &google__longrunning__operation__descriptor },
  { "ImportAgent", &google__cloud__dialogflow__v2beta1__import_agent_request__descriptor, &google__longrunning__operation__descriptor },
  { "RestoreAgent", &google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor, &google__longrunning__operation__descriptor },
};
const unsigned google__cloud__dialogflow__v2beta1__agents__method_indices_by_name[] = {
  3,        /* ExportAgent */
  0,        /* GetAgent */
  4,        /* ImportAgent */
  5,        /* RestoreAgent */
  1,        /* SearchAgents */
  2         /* TrainAgent */
};
const ProtobufCServiceDescriptor google__cloud__dialogflow__v2beta1__agents__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.Agents",
  "Agents",
  "Google__Cloud__Dialogflow__V2beta1__Agents",
  "google.cloud.dialogflow.v2beta1",
  6,
  google__cloud__dialogflow__v2beta1__agents__method_descriptors,
  google__cloud__dialogflow__v2beta1__agents__method_indices_by_name
};
void google__cloud__dialogflow__v2beta1__agents__get_agent(ProtobufCService *service,
                                                           const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *input,
                                                           Google__Cloud__Dialogflow__V2beta1__Agent_Closure closure,
                                                           void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__search_agents(ProtobufCService *service,
                                                               const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *input,
                                                               Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__train_agent(ProtobufCService *service,
                                                             const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *input,
                                                             Google__Longrunning__Operation_Closure closure,
                                                             void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__export_agent(ProtobufCService *service,
                                                              const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *input,
                                                              Google__Longrunning__Operation_Closure closure,
                                                              void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__import_agent(ProtobufCService *service,
                                                              const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *input,
                                                              Google__Longrunning__Operation_Closure closure,
                                                              void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__restore_agent(ProtobufCService *service,
                                                               const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *input,
                                                               Google__Longrunning__Operation_Closure closure,
                                                               void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__agents__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__agents__init (Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                                                       Google__Cloud__Dialogflow__V2beta1__Agents_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &google__cloud__dialogflow__v2beta1__agents__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
