/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/cloud/dialogflow/v2beta1/agent.proto */

#ifndef PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED
#define PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "annotations.pb-c.h"
#include "operations.pb-c.h"
#include "empty.pb-c.h"
#include "field_mask.pb-c.h"
#include "struct.pb-c.h"

typedef struct _Google__Cloud__Dialogflow__V2beta1__Agent Google__Cloud__Dialogflow__V2beta1__Agent;
typedef struct _Google__Cloud__Dialogflow__V2beta1__GetAgentRequest Google__Cloud__Dialogflow__V2beta1__GetAgentRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse;
typedef struct _Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse;
typedef struct _Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest;


/* --- enums --- */

/*
 * Match mode determines how intents are detected from user queries.
 */
typedef enum _Google__Cloud__Dialogflow__V2beta1__Agent__MatchMode {
  /*
   * Not specified.
   */
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_UNSPECIFIED = 0,
  /*
   * Best for agents with a small number of examples in intents and/or wide
   * use of templates syntax and composite entities.
   */
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_HYBRID = 1,
  /*
   * Can be used for agents with a large number of examples in intents,
   * especially the ones using @sys.any or very large developer entities.
   */
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_ML_ONLY = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE)
} Google__Cloud__Dialogflow__V2beta1__Agent__MatchMode;

/* --- messages --- */

/*
 * Represents a conversational agent.
 */
struct  _Google__Cloud__Dialogflow__V2beta1__Agent
{
  ProtobufCMessage base;
  /*
   * Required. The project of this agent.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
  /*
   * Required. The name of this agent.
   */
  char *display_name;
  /*
   * Required. The default language of the agent as a language tag. See
   * [Language Support](https://dialogflow.com/docs/reference/language) for a
   * list of the currently supported language codes.
   * This field cannot be set by the `Update` method.
   */
  char *default_language_code;
  /*
   * Optional. The list of all languages supported by this agent (except for the
   * `default_language_code`).
   */
  size_t n_supported_language_codes;
  char **supported_language_codes;
  /*
   * Required. The time zone of this agent from the
   * [time zone database](https://www.iana.org/time-zones), e.g.,
   * America/New_York, Europe/Paris.
   */
  char *time_zone;
  /*
   * Optional. The description of this agent.
   * The maximum length is 500 characters. If exceeded, the request is rejected.
   */
  char *description;
  /*
   * Optional. The URI of the agent's avatar.
   * Avatars are used throughout the Dialogflow console and in the self-hosted
   * [Web Demo](https://dialogflow.com/docs/integrations/web-demo) integration.
   */
  char *avatar_uri;
  /*
   * Optional. Determines whether this agent should log conversation queries.
   */
  protobuf_c_boolean enable_logging;
  /*
   * Optional. Determines how intents are detected from user queries.
   */
  Google__Cloud__Dialogflow__V2beta1__Agent__MatchMode match_mode;
  /*
   * Optional. To filter out false positive results and still get variety in
   * matched natural language inputs for your agent, you can tune the machine
   * learning classification threshold. If the returned score value is less than
   * the threshold value, then a fallback intent is be triggered or, if there
   * are no fallback intents defined, no intent will be triggered. The score
   * values range from 0.0 (completely uncertain) to 1.0 (completely certain).
   * If set to 0.0, the default of 0.3 is used.
   */
  float classification_threshold;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__agent__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENT__MATCH_MODE__MATCH_MODE_UNSPECIFIED, 0 }


/*
 * The request message for [Agents.GetAgent][google.cloud.dialogflow.v2beta1.Agents.GetAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__GetAgentRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project that the agent to fetch is associated with.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__GET_AGENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__get_agent_request__descriptor) \
    , (char *)protobuf_c_empty_string }


/*
 * The request message for [Agents.SearchAgents][google.cloud.dialogflow.v2beta1.Agents.SearchAgents].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project to list agents from.
   * Format: `projects/<Project ID or '-'>`.
   */
  char *parent;
  /*
   * Optional. The maximum number of items to return in a single page. By
   * default 100 and at most 1000.
   */
  int32_t page_size;
  /*
   * Optional. The next_page_token value returned from a previous list request.
   */
  char *page_token;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__SEARCH_AGENTS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__search_agents_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 * The response message for [Agents.SearchAgents][google.cloud.dialogflow.v2beta1.Agents.SearchAgents].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse
{
  ProtobufCMessage base;
  /*
   * The list of agents. There will be a maximum number of items returned based
   * on the page_size field in the request.
   */
  size_t n_agents;
  Google__Cloud__Dialogflow__V2beta1__Agent **agents;
  /*
   * Token to retrieve the next page of results, or empty if there are no
   * more results in the list.
   */
  char *next_page_token;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__SEARCH_AGENTS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__search_agents_response__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string }


/*
 * The request message for [Agents.TrainAgent][google.cloud.dialogflow.v2beta1.Agents.TrainAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project that the agent to train is associated with.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__TRAIN_AGENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__train_agent_request__descriptor) \
    , (char *)protobuf_c_empty_string }


/*
 * The request message for [Agents.ExportAgent][google.cloud.dialogflow.v2beta1.Agents.ExportAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project that the agent to export is associated with.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
  /*
   * Optional. The
   * [Google Cloud Storage](https://cloud.google.com/storage/docs/)
   * URI to export the agent to.
   * The format of this URI must be `gs://<bucket-name>/<object-name>`.
   * If left unspecified, the serialized agent is returned inline.
   */
  char *agent_uri;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__export_agent_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__AGENT__NOT_SET = 0,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__AGENT_AGENT_URI = 1,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__AGENT_AGENT_CONTENT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__AGENT)
} Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse__AgentCase;

/*
 * The response message for [Agents.ExportAgent][google.cloud.dialogflow.v2beta1.Agents.ExportAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse
{
  ProtobufCMessage base;
  Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse__AgentCase agent_case;
  union {
    /*
     * The URI to a file containing the exported agent. This field is populated
     * only if `agent_uri` is specified in `ExportAgentRequest`.
     */
    char *agent_uri;
    /*
     * The exported agent.
     * Example for how to export an agent to a zip file via a command line:
     * <pre>curl \
     *   'https://dialogflow.googleapis.com/v2beta1/projects/&lt;project_name&gt;/agent:export'\
     *   -X POST \
     *   -H 'Authorization: Bearer '$(gcloud auth application-default
     *   print-access-token) \
     *   -H 'Accept: application/json' \
     *   -H 'Content-Type: application/json' \
     *   --compressed \
     *   --data-binary '{}' \
     * | grep agentContent | sed -e 's/.*"agentContent": "\([^"]*\)".* \1/' \
     * | base64 --decode > &lt;agent zip file&gt;</pre>
     */
    ProtobufCBinaryData agent_content;
  };
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__export_agent_response__descriptor) \
    , GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__EXPORT_AGENT_RESPONSE__AGENT__NOT_SET, {0} }


typedef enum {
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__AGENT__NOT_SET = 0,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__AGENT_AGENT_URI = 2,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__AGENT_AGENT_CONTENT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__AGENT)
} Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest__AgentCase;

/*
 * The request message for [Agents.ImportAgent][google.cloud.dialogflow.v2beta1.Agents.ImportAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project that the agent to import is associated with.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
  Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest__AgentCase agent_case;
  union {
    /*
     * The URI to a Google Cloud Storage file containing the agent to import.
     * Note: The URI must start with "gs://".
     */
    char *agent_uri;
    /*
     * The agent to import.
     * Example for how to import an agent via the command line:
     * <pre>curl \
     *   'https://dialogflow.googleapis.com/v2beta1/projects/&lt;project_name&gt;/agent:import\
     *    -X POST \
     *    -H 'Authorization: Bearer '$(gcloud auth application-default
     *    print-access-token) \
     *    -H 'Accept: application/json' \
     *    -H 'Content-Type: application/json' \
     *    --compressed \
     *    --data-binary "{
     *       'agentContent': '$(cat &lt;agent zip file&gt; | base64 -w 0)'
     *    }"</pre>
     */
    ProtobufCBinaryData agent_content;
  };
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__import_agent_request__descriptor) \
    , (char *)protobuf_c_empty_string, GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__IMPORT_AGENT_REQUEST__AGENT__NOT_SET, {0} }


typedef enum {
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__AGENT__NOT_SET = 0,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__AGENT_AGENT_URI = 2,
  GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__AGENT_AGENT_CONTENT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__AGENT)
} Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest__AgentCase;

/*
 * The request message for [Agents.RestoreAgent][google.cloud.dialogflow.v2beta1.Agents.RestoreAgent].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest
{
  ProtobufCMessage base;
  /*
   * Required. The project that the agent to restore is associated with.
   * Format: `projects/<Project ID>`.
   */
  char *parent;
  Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest__AgentCase agent_case;
  union {
    /*
     * The URI to a Google Cloud Storage file containing the agent to restore.
     * Note: The URI must start with "gs://".
     */
    char *agent_uri;
    /*
     * The agent to restore.
     * Example for how to restore an agent via the command line:
     * <pre>curl \
     *   'https://dialogflow.googleapis.com/v2beta1/projects/&lt;project_name&gt;/agent:restore\
     *    -X POST \
     *    -H 'Authorization: Bearer '$(gcloud auth application-default
     *    print-access-token) \
     *    -H 'Accept: application/json' \
     *    -H 'Content-Type: application/json' \
     *    --compressed \
     *    --data-binary "{
     *        'agentContent': '$(cat &lt;agent zip file&gt; | base64 -w 0)'
     *    }"</pre>
     */
    ProtobufCBinaryData agent_content;
  };
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor) \
    , (char *)protobuf_c_empty_string, GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__RESTORE_AGENT_REQUEST__AGENT__NOT_SET, {0} }


/* Google__Cloud__Dialogflow__V2beta1__Agent methods */
void   google__cloud__dialogflow__v2beta1__agent__init
                     (Google__Cloud__Dialogflow__V2beta1__Agent         *message);
size_t google__cloud__dialogflow__v2beta1__agent__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__Agent   *message);
size_t google__cloud__dialogflow__v2beta1__agent__pack
                     (const Google__Cloud__Dialogflow__V2beta1__Agent   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__agent__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__Agent   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__Agent *
       google__cloud__dialogflow__v2beta1__agent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__agent__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__Agent *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__GetAgentRequest methods */
void   google__cloud__dialogflow__v2beta1__get_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__GetAgentRequest         *message);
size_t google__cloud__dialogflow__v2beta1__get_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest   *message);
size_t google__cloud__dialogflow__v2beta1__get_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__get_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *
       google__cloud__dialogflow__v2beta1__get_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__get_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest methods */
void   google__cloud__dialogflow__v2beta1__search_agents_request__init
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest         *message);
size_t google__cloud__dialogflow__v2beta1__search_agents_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest   *message);
size_t google__cloud__dialogflow__v2beta1__search_agents_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__search_agents_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *
       google__cloud__dialogflow__v2beta1__search_agents_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__search_agents_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse methods */
void   google__cloud__dialogflow__v2beta1__search_agents_response__init
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse         *message);
size_t google__cloud__dialogflow__v2beta1__search_agents_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse   *message);
size_t google__cloud__dialogflow__v2beta1__search_agents_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__search_agents_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *
       google__cloud__dialogflow__v2beta1__search_agents_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__search_agents_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest methods */
void   google__cloud__dialogflow__v2beta1__train_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest         *message);
size_t google__cloud__dialogflow__v2beta1__train_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest   *message);
size_t google__cloud__dialogflow__v2beta1__train_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__train_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *
       google__cloud__dialogflow__v2beta1__train_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__train_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest methods */
void   google__cloud__dialogflow__v2beta1__export_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest         *message);
size_t google__cloud__dialogflow__v2beta1__export_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest   *message);
size_t google__cloud__dialogflow__v2beta1__export_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__export_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *
       google__cloud__dialogflow__v2beta1__export_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__export_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse methods */
void   google__cloud__dialogflow__v2beta1__export_agent_response__init
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse         *message);
size_t google__cloud__dialogflow__v2beta1__export_agent_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse   *message);
size_t google__cloud__dialogflow__v2beta1__export_agent_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__export_agent_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *
       google__cloud__dialogflow__v2beta1__export_agent_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__export_agent_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest methods */
void   google__cloud__dialogflow__v2beta1__import_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest         *message);
size_t google__cloud__dialogflow__v2beta1__import_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest   *message);
size_t google__cloud__dialogflow__v2beta1__import_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__import_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *
       google__cloud__dialogflow__v2beta1__import_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__import_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest methods */
void   google__cloud__dialogflow__v2beta1__restore_agent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest         *message);
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest   *message);
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__restore_agent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *
       google__cloud__dialogflow__v2beta1__restore_agent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__restore_agent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Google__Cloud__Dialogflow__V2beta1__Agent_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__Agent *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__GetAgentRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__ExportAgentResponse *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Google__Cloud__Dialogflow__V2beta1__Agents_Service Google__Cloud__Dialogflow__V2beta1__Agents_Service;
struct _Google__Cloud__Dialogflow__V2beta1__Agents_Service
{
  ProtobufCService base;
  void (*get_agent)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                    const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *input,
                    Google__Cloud__Dialogflow__V2beta1__Agent_Closure closure,
                    void *closure_data);
  void (*search_agents)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                        const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *input,
                        Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse_Closure closure,
                        void *closure_data);
  void (*train_agent)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                      const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *input,
                      Google__Longrunning__Operation_Closure closure,
                      void *closure_data);
  void (*export_agent)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                       const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *input,
                       Google__Longrunning__Operation_Closure closure,
                       void *closure_data);
  void (*import_agent)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                       const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *input,
                       Google__Longrunning__Operation_Closure closure,
                       void *closure_data);
  void (*restore_agent)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                        const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *input,
                        Google__Longrunning__Operation_Closure closure,
                        void *closure_data);
};
typedef void (*Google__Cloud__Dialogflow__V2beta1__Agents_ServiceDestroy)(Google__Cloud__Dialogflow__V2beta1__Agents_Service *);
void google__cloud__dialogflow__v2beta1__agents__init (Google__Cloud__Dialogflow__V2beta1__Agents_Service *service,
                                                       Google__Cloud__Dialogflow__V2beta1__Agents_ServiceDestroy destroy);
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENTS__BASE_INIT \
    { &google__cloud__dialogflow__v2beta1__agents__descriptor, protobuf_c_service_invoke_internal, NULL }
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENTS__INIT(function_prefix__) \
    { GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__AGENTS__BASE_INIT,\
      function_prefix__ ## get_agent,\
      function_prefix__ ## search_agents,\
      function_prefix__ ## train_agent,\
      function_prefix__ ## export_agent,\
      function_prefix__ ## import_agent,\
      function_prefix__ ## restore_agent  }
void google__cloud__dialogflow__v2beta1__agents__get_agent(ProtobufCService *service,
                                                           const Google__Cloud__Dialogflow__V2beta1__GetAgentRequest *input,
                                                           Google__Cloud__Dialogflow__V2beta1__Agent_Closure closure,
                                                           void *closure_data);
void google__cloud__dialogflow__v2beta1__agents__search_agents(ProtobufCService *service,
                                                               const Google__Cloud__Dialogflow__V2beta1__SearchAgentsRequest *input,
                                                               Google__Cloud__Dialogflow__V2beta1__SearchAgentsResponse_Closure closure,
                                                               void *closure_data);
void google__cloud__dialogflow__v2beta1__agents__train_agent(ProtobufCService *service,
                                                             const Google__Cloud__Dialogflow__V2beta1__TrainAgentRequest *input,
                                                             Google__Longrunning__Operation_Closure closure,
                                                             void *closure_data);
void google__cloud__dialogflow__v2beta1__agents__export_agent(ProtobufCService *service,
                                                              const Google__Cloud__Dialogflow__V2beta1__ExportAgentRequest *input,
                                                              Google__Longrunning__Operation_Closure closure,
                                                              void *closure_data);
void google__cloud__dialogflow__v2beta1__agents__import_agent(ProtobufCService *service,
                                                              const Google__Cloud__Dialogflow__V2beta1__ImportAgentRequest *input,
                                                              Google__Longrunning__Operation_Closure closure,
                                                              void *closure_data);
void google__cloud__dialogflow__v2beta1__agents__restore_agent(ProtobufCService *service,
                                                               const Google__Cloud__Dialogflow__V2beta1__RestoreAgentRequest *input,
                                                               Google__Longrunning__Operation_Closure closure,
                                                               void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__agent__descriptor;
extern const ProtobufCEnumDescriptor    google__cloud__dialogflow__v2beta1__agent__match_mode__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__get_agent_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__search_agents_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__search_agents_response__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__train_agent_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__export_agent_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__export_agent_response__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__import_agent_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__restore_agent_request__descriptor;
extern const ProtobufCServiceDescriptor google__cloud__dialogflow__v2beta1__agents__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fagent_2eproto__INCLUDED */
