/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/cloud/dialogflow/v2beta1/entity_type.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "entity_type.pb-c.h"
void   google__cloud__dialogflow__v2beta1__entity_type__entity__init
                     (Google__Cloud__Dialogflow__V2beta1__EntityType__Entity         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__EntityType__Entity init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__ENTITY__INIT;
  *message = init_value;
}
void   google__cloud__dialogflow__v2beta1__entity_type__init
                     (Google__Cloud__Dialogflow__V2beta1__EntityType         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__EntityType init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__entity_type__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__EntityType *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__entity_type__pack
                     (const Google__Cloud__Dialogflow__V2beta1__EntityType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__entity_type__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__EntityType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__EntityType *
       google__cloud__dialogflow__v2beta1__entity_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__EntityType *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__entity_type__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__entity_type__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__EntityType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__list_entity_types_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__LIST_ENTITY_TYPES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *
       google__cloud__dialogflow__v2beta1__list_entity_types_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__list_entity_types_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__list_entity_types_response__init
                     (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__LIST_ENTITY_TYPES_RESPONSE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__list_entity_types_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *
       google__cloud__dialogflow__v2beta1__list_entity_types_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__list_entity_types_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__get_entity_type_request__init
                     (Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__GET_ENTITY_TYPE_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__get_entity_type_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__get_entity_type_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__get_entity_type_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *
       google__cloud__dialogflow__v2beta1__get_entity_type_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__get_entity_type_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__create_entity_type_request__init
                     (Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__CREATE_ENTITY_TYPE_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__create_entity_type_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__create_entity_type_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__create_entity_type_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *
       google__cloud__dialogflow__v2beta1__create_entity_type_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__create_entity_type_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__update_entity_type_request__init
                     (Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__UPDATE_ENTITY_TYPE_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__update_entity_type_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__update_entity_type_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__update_entity_type_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *
       google__cloud__dialogflow__v2beta1__update_entity_type_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__update_entity_type_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__delete_entity_type_request__init
                     (Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__DELETE_ENTITY_TYPE_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__delete_entity_type_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__delete_entity_type_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__delete_entity_type_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *
       google__cloud__dialogflow__v2beta1__delete_entity_type_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__delete_entity_type_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_UPDATE_ENTITY_TYPES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *
       google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_UPDATE_ENTITY_TYPES_RESPONSE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *
       google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_DELETE_ENTITY_TYPES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *
       google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_create_entities_request__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_CREATE_ENTITIES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_create_entities_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_create_entities_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_create_entities_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *
       google__cloud__dialogflow__v2beta1__batch_create_entities_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_create_entities_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entities_request__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_UPDATE_ENTITIES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entities_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entities_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_update_entities_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *
       google__cloud__dialogflow__v2beta1__batch_update_entities_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_update_entities_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__batch_delete_entities_request__init
                     (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__BATCH_DELETE_ENTITIES_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entities_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entities_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__batch_delete_entities_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *
       google__cloud__dialogflow__v2beta1__batch_delete_entities_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__batch_delete_entities_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__entity_type_batch__init
                     (Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE_BATCH__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__entity_type_batch__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__entity_type_batch__pack
                     (const Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__entity_type_batch__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *
       google__cloud__dialogflow__v2beta1__entity_type_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__entity_type_batch__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__entity_type__entity__field_descriptors[2] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType__Entity, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "synonyms",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType__Entity, n_synonyms),
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType__Entity, synonyms),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__entity_type__entity__field_indices_by_name[] = {
  1,   /* field[1] = synonyms */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__entity_type__entity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__entity_type__entity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityType.Entity",
  "Entity",
  "Google__Cloud__Dialogflow__V2beta1__EntityType__Entity",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__EntityType__Entity),
  2,
  google__cloud__dialogflow__v2beta1__entity_type__entity__field_descriptors,
  google__cloud__dialogflow__v2beta1__entity_type__entity__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__entity_type__entity__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__entity_type__entity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue google__cloud__dialogflow__v2beta1__entity_type__kind__enum_values_by_number[3] =
{
  { "KIND_UNSPECIFIED", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__KIND__KIND_UNSPECIFIED", 0 },
  { "KIND_MAP", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__KIND__KIND_MAP", 1 },
  { "KIND_LIST", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__KIND__KIND_LIST", 2 },
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__entity_type__kind__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex google__cloud__dialogflow__v2beta1__entity_type__kind__enum_values_by_name[3] =
{
  { "KIND_LIST", 2 },
  { "KIND_MAP", 1 },
  { "KIND_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor google__cloud__dialogflow__v2beta1__entity_type__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityType.Kind",
  "Kind",
  "Google__Cloud__Dialogflow__V2beta1__EntityType__Kind",
  "google.cloud.dialogflow.v2beta1",
  3,
  google__cloud__dialogflow__v2beta1__entity_type__kind__enum_values_by_number,
  3,
  google__cloud__dialogflow__v2beta1__entity_type__kind__enum_values_by_name,
  1,
  google__cloud__dialogflow__v2beta1__entity_type__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__enum_values_by_number[2] =
{
  { "AUTO_EXPANSION_MODE_UNSPECIFIED", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__AUTO_EXPANSION_MODE__AUTO_EXPANSION_MODE_UNSPECIFIED", 0 },
  { "AUTO_EXPANSION_MODE_DEFAULT", "GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ENTITY_TYPE__AUTO_EXPANSION_MODE__AUTO_EXPANSION_MODE_DEFAULT", 1 },
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__enum_values_by_name[2] =
{
  { "AUTO_EXPANSION_MODE_DEFAULT", 1 },
  { "AUTO_EXPANSION_MODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityType.AutoExpansionMode",
  "AutoExpansionMode",
  "Google__Cloud__Dialogflow__V2beta1__EntityType__AutoExpansionMode",
  "google.cloud.dialogflow.v2beta1",
  2,
  google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__enum_values_by_number,
  2,
  google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__enum_values_by_name,
  1,
  google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__entity_type__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, kind),
    &google__cloud__dialogflow__v2beta1__entity_type__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_expansion_mode",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, auto_expansion_mode),
    &google__cloud__dialogflow__v2beta1__entity_type__auto_expansion_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entities",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, n_entities),
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityType, entities),
    &google__cloud__dialogflow__v2beta1__entity_type__entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__entity_type__field_indices_by_name[] = {
  3,   /* field[3] = auto_expansion_mode */
  1,   /* field[1] = display_name */
  4,   /* field[4] = entities */
  2,   /* field[2] = kind */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__entity_type__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__entity_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityType",
  "EntityType",
  "Google__Cloud__Dialogflow__V2beta1__EntityType",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__EntityType),
  5,
  google__cloud__dialogflow__v2beta1__entity_type__field_descriptors,
  google__cloud__dialogflow__v2beta1__entity_type__field_indices_by_name,
  2,  google__cloud__dialogflow__v2beta1__entity_type__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__entity_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__list_entity_types_request__field_descriptors[4] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest, page_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_token",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest, page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__list_entity_types_request__field_indices_by_name[] = {
  1,   /* field[1] = language_code */
  2,   /* field[2] = page_size */
  3,   /* field[3] = page_token */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__list_entity_types_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.ListEntityTypesRequest",
  "ListEntityTypesRequest",
  "Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest),
  4,
  google__cloud__dialogflow__v2beta1__list_entity_types_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__list_entity_types_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__list_entity_types_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__list_entity_types_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__list_entity_types_response__field_descriptors[2] =
{
  {
    "entity_types",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse, n_entity_types),
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse, entity_types),
    &google__cloud__dialogflow__v2beta1__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_page_token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse, next_page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__list_entity_types_response__field_indices_by_name[] = {
  0,   /* field[0] = entity_types */
  1,   /* field[1] = next_page_token */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__list_entity_types_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.ListEntityTypesResponse",
  "ListEntityTypesResponse",
  "Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse),
  2,
  google__cloud__dialogflow__v2beta1__list_entity_types_response__field_descriptors,
  google__cloud__dialogflow__v2beta1__list_entity_types_response__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__list_entity_types_response__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__list_entity_types_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__get_entity_type_request__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__get_entity_type_request__field_indices_by_name[] = {
  1,   /* field[1] = language_code */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__get_entity_type_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.GetEntityTypeRequest",
  "GetEntityTypeRequest",
  "Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest),
  2,
  google__cloud__dialogflow__v2beta1__get_entity_type_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__get_entity_type_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__get_entity_type_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__get_entity_type_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__create_entity_type_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest, entity_type),
    &google__cloud__dialogflow__v2beta1__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__create_entity_type_request__field_indices_by_name[] = {
  1,   /* field[1] = entity_type */
  2,   /* field[2] = language_code */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__create_entity_type_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.CreateEntityTypeRequest",
  "CreateEntityTypeRequest",
  "Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest),
  3,
  google__cloud__dialogflow__v2beta1__create_entity_type_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__create_entity_type_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__create_entity_type_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__create_entity_type_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__update_entity_type_request__field_descriptors[3] =
{
  {
    "entity_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest, entity_type),
    &google__cloud__dialogflow__v2beta1__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_mask",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest, update_mask),
    &google__protobuf__field_mask__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__update_entity_type_request__field_indices_by_name[] = {
  0,   /* field[0] = entity_type */
  1,   /* field[1] = language_code */
  2,   /* field[2] = update_mask */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__update_entity_type_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.UpdateEntityTypeRequest",
  "UpdateEntityTypeRequest",
  "Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest),
  3,
  google__cloud__dialogflow__v2beta1__update_entity_type_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__update_entity_type_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__update_entity_type_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__update_entity_type_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__delete_entity_type_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__delete_entity_type_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__delete_entity_type_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.DeleteEntityTypeRequest",
  "DeleteEntityTypeRequest",
  "Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest),
  1,
  google__cloud__dialogflow__v2beta1__delete_entity_type_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__delete_entity_type_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__delete_entity_type_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__delete_entity_type_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__field_descriptors[5] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity_type_batch_uri",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, entity_type_batch_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, entity_type_batch_uri),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity_type_batch_inline",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, entity_type_batch_case),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, entity_type_batch_inline),
    &google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_mask",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest, update_mask),
    &google__protobuf__field_mask__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__field_indices_by_name[] = {
  2,   /* field[2] = entity_type_batch_inline */
  1,   /* field[1] = entity_type_batch_uri */
  3,   /* field[3] = language_code */
  0,   /* field[0] = parent */
  4,   /* field[4] = update_mask */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesRequest",
  "BatchUpdateEntityTypesRequest",
  "Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest),
  5,
  google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__field_descriptors[1] =
{
  {
    "entity_types",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse, n_entity_types),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse, entity_types),
    &google__cloud__dialogflow__v2beta1__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__field_indices_by_name[] = {
  0,   /* field[0] = entity_types */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesResponse",
  "BatchUpdateEntityTypesResponse",
  "Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesResponse),
  1,
  google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_update_entity_types_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__field_descriptors[2] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity_type_names",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest, n_entity_type_names),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest, entity_type_names),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__field_indices_by_name[] = {
  1,   /* field[1] = entity_type_names */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchDeleteEntityTypesRequest",
  "BatchDeleteEntityTypesRequest",
  "Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest),
  2,
  google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_create_entities_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entities",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest, n_entities),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest, entities),
    &google__cloud__dialogflow__v2beta1__entity_type__entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_create_entities_request__field_indices_by_name[] = {
  1,   /* field[1] = entities */
  2,   /* field[2] = language_code */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_create_entities_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchCreateEntitiesRequest",
  "BatchCreateEntitiesRequest",
  "Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest),
  3,
  google__cloud__dialogflow__v2beta1__batch_create_entities_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_create_entities_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_create_entities_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_create_entities_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_update_entities_request__field_descriptors[4] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entities",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest, n_entities),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest, entities),
    &google__cloud__dialogflow__v2beta1__entity_type__entity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest, update_mask),
    &google__protobuf__field_mask__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_update_entities_request__field_indices_by_name[] = {
  1,   /* field[1] = entities */
  2,   /* field[2] = language_code */
  0,   /* field[0] = parent */
  3,   /* field[3] = update_mask */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_update_entities_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchUpdateEntitiesRequest",
  "BatchUpdateEntitiesRequest",
  "Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest),
  4,
  google__cloud__dialogflow__v2beta1__batch_update_entities_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_update_entities_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_update_entities_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_update_entities_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__batch_delete_entities_request__field_descriptors[3] =
{
  {
    "parent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest, parent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entity_values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest, n_entity_values),
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest, entity_values),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language_code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest, language_code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__batch_delete_entities_request__field_indices_by_name[] = {
  1,   /* field[1] = entity_values */
  2,   /* field[2] = language_code */
  0,   /* field[0] = parent */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__batch_delete_entities_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.BatchDeleteEntitiesRequest",
  "BatchDeleteEntitiesRequest",
  "Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest),
  3,
  google__cloud__dialogflow__v2beta1__batch_delete_entities_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__batch_delete_entities_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__batch_delete_entities_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__batch_delete_entities_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__entity_type_batch__field_descriptors[1] =
{
  {
    "entity_types",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch, n_entity_types),
    offsetof(Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch, entity_types),
    &google__cloud__dialogflow__v2beta1__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__entity_type_batch__field_indices_by_name[] = {
  0,   /* field[0] = entity_types */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__entity_type_batch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__entity_type_batch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityTypeBatch",
  "EntityTypeBatch",
  "Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__EntityTypeBatch),
  1,
  google__cloud__dialogflow__v2beta1__entity_type_batch__field_descriptors,
  google__cloud__dialogflow__v2beta1__entity_type_batch__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__entity_type_batch__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__entity_type_batch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor google__cloud__dialogflow__v2beta1__entity_types__method_descriptors[10] =
{
  { "ListEntityTypes", &google__cloud__dialogflow__v2beta1__list_entity_types_request__descriptor, &google__cloud__dialogflow__v2beta1__list_entity_types_response__descriptor },
  { "GetEntityType", &google__cloud__dialogflow__v2beta1__get_entity_type_request__descriptor, &google__cloud__dialogflow__v2beta1__entity_type__descriptor },
  { "CreateEntityType", &google__cloud__dialogflow__v2beta1__create_entity_type_request__descriptor, &google__cloud__dialogflow__v2beta1__entity_type__descriptor },
  { "UpdateEntityType", &google__cloud__dialogflow__v2beta1__update_entity_type_request__descriptor, &google__cloud__dialogflow__v2beta1__entity_type__descriptor },
  { "DeleteEntityType", &google__cloud__dialogflow__v2beta1__delete_entity_type_request__descriptor, &google__protobuf__empty__descriptor },
  { "BatchUpdateEntityTypes", &google__cloud__dialogflow__v2beta1__batch_update_entity_types_request__descriptor, &google__longrunning__operation__descriptor },
  { "BatchDeleteEntityTypes", &google__cloud__dialogflow__v2beta1__batch_delete_entity_types_request__descriptor, &google__longrunning__operation__descriptor },
  { "BatchCreateEntities", &google__cloud__dialogflow__v2beta1__batch_create_entities_request__descriptor, &google__longrunning__operation__descriptor },
  { "BatchUpdateEntities", &google__cloud__dialogflow__v2beta1__batch_update_entities_request__descriptor, &google__longrunning__operation__descriptor },
  { "BatchDeleteEntities", &google__cloud__dialogflow__v2beta1__batch_delete_entities_request__descriptor, &google__longrunning__operation__descriptor },
};
const unsigned google__cloud__dialogflow__v2beta1__entity_types__method_indices_by_name[] = {
  7,        /* BatchCreateEntities */
  9,        /* BatchDeleteEntities */
  6,        /* BatchDeleteEntityTypes */
  8,        /* BatchUpdateEntities */
  5,        /* BatchUpdateEntityTypes */
  2,        /* CreateEntityType */
  4,        /* DeleteEntityType */
  1,        /* GetEntityType */
  0,        /* ListEntityTypes */
  3         /* UpdateEntityType */
};
const ProtobufCServiceDescriptor google__cloud__dialogflow__v2beta1__entity_types__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.EntityTypes",
  "EntityTypes",
  "Google__Cloud__Dialogflow__V2beta1__EntityTypes",
  "google.cloud.dialogflow.v2beta1",
  10,
  google__cloud__dialogflow__v2beta1__entity_types__method_descriptors,
  google__cloud__dialogflow__v2beta1__entity_types__method_indices_by_name
};
void google__cloud__dialogflow__v2beta1__entity_types__list_entity_types(ProtobufCService *service,
                                                                         const Google__Cloud__Dialogflow__V2beta1__ListEntityTypesRequest *input,
                                                                         Google__Cloud__Dialogflow__V2beta1__ListEntityTypesResponse_Closure closure,
                                                                         void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__get_entity_type(ProtobufCService *service,
                                                                       const Google__Cloud__Dialogflow__V2beta1__GetEntityTypeRequest *input,
                                                                       Google__Cloud__Dialogflow__V2beta1__EntityType_Closure closure,
                                                                       void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__create_entity_type(ProtobufCService *service,
                                                                          const Google__Cloud__Dialogflow__V2beta1__CreateEntityTypeRequest *input,
                                                                          Google__Cloud__Dialogflow__V2beta1__EntityType_Closure closure,
                                                                          void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__update_entity_type(ProtobufCService *service,
                                                                          const Google__Cloud__Dialogflow__V2beta1__UpdateEntityTypeRequest *input,
                                                                          Google__Cloud__Dialogflow__V2beta1__EntityType_Closure closure,
                                                                          void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__delete_entity_type(ProtobufCService *service,
                                                                          const Google__Cloud__Dialogflow__V2beta1__DeleteEntityTypeRequest *input,
                                                                          Google__Protobuf__Empty_Closure closure,
                                                                          void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__batch_update_entity_types(ProtobufCService *service,
                                                                                 const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntityTypesRequest *input,
                                                                                 Google__Longrunning__Operation_Closure closure,
                                                                                 void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__batch_delete_entity_types(ProtobufCService *service,
                                                                                 const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntityTypesRequest *input,
                                                                                 Google__Longrunning__Operation_Closure closure,
                                                                                 void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__batch_create_entities(ProtobufCService *service,
                                                                             const Google__Cloud__Dialogflow__V2beta1__BatchCreateEntitiesRequest *input,
                                                                             Google__Longrunning__Operation_Closure closure,
                                                                             void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__batch_update_entities(ProtobufCService *service,
                                                                             const Google__Cloud__Dialogflow__V2beta1__BatchUpdateEntitiesRequest *input,
                                                                             Google__Longrunning__Operation_Closure closure,
                                                                             void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__batch_delete_entities(ProtobufCService *service,
                                                                             const Google__Cloud__Dialogflow__V2beta1__BatchDeleteEntitiesRequest *input,
                                                                             Google__Longrunning__Operation_Closure closure,
                                                                             void *closure_data)
{
  assert(service->descriptor == &google__cloud__dialogflow__v2beta1__entity_types__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__cloud__dialogflow__v2beta1__entity_types__init (Google__Cloud__Dialogflow__V2beta1__EntityTypes_Service *service,
                                                             Google__Cloud__Dialogflow__V2beta1__EntityTypes_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &google__cloud__dialogflow__v2beta1__entity_types__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
