/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/cloud/dialogflow/v2beta1/knowledge_base.proto */

#ifndef PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fknowledge_5fbase_2eproto__INCLUDED
#define PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fknowledge_5fbase_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "annotations.pb-c.h"
#include "empty.pb-c.h"
#include "field_mask.pb-c.h"

typedef struct _Google__Cloud__Dialogflow__V2beta1__KnowledgeBase Google__Cloud__Dialogflow__V2beta1__KnowledgeBase;
typedef struct _Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse;
typedef struct _Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest;
typedef struct _Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest;


/* --- enums --- */


/* --- messages --- */

/*
 * Represents knowledge base resource.
 */
struct  _Google__Cloud__Dialogflow__V2beta1__KnowledgeBase
{
  ProtobufCMessage base;
  /*
   * The knowledge base resource name.
   * The name must be empty when creating a knowledge base.
   * Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
   */
  char *name;
  /*
   * Required. The display name of the knowledge base. The name must be 1024
   * bytes or less; otherwise, the creation request fails.
   */
  char *display_name;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__KNOWLEDGE_BASE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__knowledge_base__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Request message for [KnowledgeBases.ListKnowledgeBases][google.cloud.dialogflow.v2beta1.KnowledgeBases.ListKnowledgeBases].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest
{
  ProtobufCMessage base;
  /*
   * Required. The agent to list of knowledge bases for.
   * Format: `projects/<Project ID>/agent`.
   */
  char *parent;
  /*
   * Optional. The maximum number of items to return in a single page. By
   * default 10 and at most 100.
   */
  int32_t page_size;
  /*
   * Optional. The next_page_token value returned from a previous list request.
   */
  char *page_token;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__LIST_KNOWLEDGE_BASES_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 * Response message for [KnowledgeBases.ListKnowledgeBases][google.cloud.dialogflow.v2beta1.KnowledgeBases.ListKnowledgeBases].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse
{
  ProtobufCMessage base;
  /*
   * The list of knowledge bases.
   */
  size_t n_knowledge_bases;
  Google__Cloud__Dialogflow__V2beta1__KnowledgeBase **knowledge_bases;
  /*
   * Token to retrieve the next page of results, or empty if there are no
   * more results in the list.
   */
  char *next_page_token;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__LIST_KNOWLEDGE_BASES_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string }


/*
 * Request message for [KnowledgeBase.GetDocument][].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest
{
  ProtobufCMessage base;
  /*
   * Required. The name of the knowledge base to retrieve.
   * Format `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
   */
  char *name;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__GET_KNOWLEDGE_BASE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__get_knowledge_base_request__descriptor) \
    , (char *)protobuf_c_empty_string }


/*
 * Request message for [KnowledgeBases.CreateKnowledgeBase][google.cloud.dialogflow.v2beta1.KnowledgeBases.CreateKnowledgeBase].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest
{
  ProtobufCMessage base;
  /*
   * Required. The agent to create a knowledge base for.
   * Format: `projects/<Project ID>/agent`.
   */
  char *parent;
  /*
   * Required. The knowledge base to create.
   */
  Google__Cloud__Dialogflow__V2beta1__KnowledgeBase *knowledge_base;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__CREATE_KNOWLEDGE_BASE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__create_knowledge_base_request__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


/*
 * Request message for [KnowledgeBases.DeleteKnowledgeBase][google.cloud.dialogflow.v2beta1.KnowledgeBases.DeleteKnowledgeBase].
 */
struct  _Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest
{
  ProtobufCMessage base;
  /*
   * Required. The name of the knowledge base to delete.
   * Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base ID>`.
   */
  char *name;
  /*
   * Optional. Force deletes the knowledge base. When set to true, any documents
   * in the knowledge base are also deleted.
   */
  protobuf_c_boolean force;
};
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__DELETE_KNOWLEDGE_BASE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/* Google__Cloud__Dialogflow__V2beta1__KnowledgeBase methods */
void   google__cloud__dialogflow__v2beta1__knowledge_base__init
                     (Google__Cloud__Dialogflow__V2beta1__KnowledgeBase         *message);
size_t google__cloud__dialogflow__v2beta1__knowledge_base__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__KnowledgeBase   *message);
size_t google__cloud__dialogflow__v2beta1__knowledge_base__pack
                     (const Google__Cloud__Dialogflow__V2beta1__KnowledgeBase   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__knowledge_base__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__KnowledgeBase   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__KnowledgeBase *
       google__cloud__dialogflow__v2beta1__knowledge_base__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__knowledge_base__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__KnowledgeBase *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest methods */
void   google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__init
                     (Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest         *message);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest   *message);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest *
       google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse methods */
void   google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__init
                     (Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse         *message);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse   *message);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse *
       google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest methods */
void   google__cloud__dialogflow__v2beta1__get_knowledge_base_request__init
                     (Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest         *message);
size_t google__cloud__dialogflow__v2beta1__get_knowledge_base_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest   *message);
size_t google__cloud__dialogflow__v2beta1__get_knowledge_base_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__get_knowledge_base_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest *
       google__cloud__dialogflow__v2beta1__get_knowledge_base_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__get_knowledge_base_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest methods */
void   google__cloud__dialogflow__v2beta1__create_knowledge_base_request__init
                     (Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest         *message);
size_t google__cloud__dialogflow__v2beta1__create_knowledge_base_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest   *message);
size_t google__cloud__dialogflow__v2beta1__create_knowledge_base_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__create_knowledge_base_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest *
       google__cloud__dialogflow__v2beta1__create_knowledge_base_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__create_knowledge_base_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest *message,
                      ProtobufCAllocator *allocator);
/* Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest methods */
void   google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__init
                     (Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest         *message);
size_t google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest   *message);
size_t google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest   *message,
                      uint8_t             *out);
size_t google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest   *message,
                      ProtobufCBuffer     *buffer);
Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest *
       google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Google__Cloud__Dialogflow__V2beta1__KnowledgeBase_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__KnowledgeBase *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest *message,
                  void *closure_data);
typedef void (*Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest_Closure)
                 (const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service;
struct _Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service
{
  ProtobufCService base;
  void (*list_knowledge_bases)(Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *service,
                               const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest *input,
                               Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse_Closure closure,
                               void *closure_data);
  void (*get_knowledge_base)(Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *service,
                             const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest *input,
                             Google__Cloud__Dialogflow__V2beta1__KnowledgeBase_Closure closure,
                             void *closure_data);
  void (*create_knowledge_base)(Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *service,
                                const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest *input,
                                Google__Cloud__Dialogflow__V2beta1__KnowledgeBase_Closure closure,
                                void *closure_data);
  void (*delete_knowledge_base)(Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *service,
                                const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest *input,
                                Google__Protobuf__Empty_Closure closure,
                                void *closure_data);
};
typedef void (*Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_ServiceDestroy)(Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *);
void google__cloud__dialogflow__v2beta1__knowledge_bases__init (Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_Service *service,
                                                                Google__Cloud__Dialogflow__V2beta1__KnowledgeBases_ServiceDestroy destroy);
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__KNOWLEDGE_BASES__BASE_INIT \
    { &google__cloud__dialogflow__v2beta1__knowledge_bases__descriptor, protobuf_c_service_invoke_internal, NULL }
#define GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__KNOWLEDGE_BASES__INIT(function_prefix__) \
    { GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__KNOWLEDGE_BASES__BASE_INIT,\
      function_prefix__ ## list_knowledge_bases,\
      function_prefix__ ## get_knowledge_base,\
      function_prefix__ ## create_knowledge_base,\
      function_prefix__ ## delete_knowledge_base  }
void google__cloud__dialogflow__v2beta1__knowledge_bases__list_knowledge_bases(ProtobufCService *service,
                                                                               const Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesRequest *input,
                                                                               Google__Cloud__Dialogflow__V2beta1__ListKnowledgeBasesResponse_Closure closure,
                                                                               void *closure_data);
void google__cloud__dialogflow__v2beta1__knowledge_bases__get_knowledge_base(ProtobufCService *service,
                                                                             const Google__Cloud__Dialogflow__V2beta1__GetKnowledgeBaseRequest *input,
                                                                             Google__Cloud__Dialogflow__V2beta1__KnowledgeBase_Closure closure,
                                                                             void *closure_data);
void google__cloud__dialogflow__v2beta1__knowledge_bases__create_knowledge_base(ProtobufCService *service,
                                                                                const Google__Cloud__Dialogflow__V2beta1__CreateKnowledgeBaseRequest *input,
                                                                                Google__Cloud__Dialogflow__V2beta1__KnowledgeBase_Closure closure,
                                                                                void *closure_data);
void google__cloud__dialogflow__v2beta1__knowledge_bases__delete_knowledge_base(ProtobufCService *service,
                                                                                const Google__Cloud__Dialogflow__V2beta1__DeleteKnowledgeBaseRequest *input,
                                                                                Google__Protobuf__Empty_Closure closure,
                                                                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__knowledge_base__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__list_knowledge_bases_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__list_knowledge_bases_response__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__get_knowledge_base_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__create_knowledge_base_request__descriptor;
extern const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__delete_knowledge_base_request__descriptor;
extern const ProtobufCServiceDescriptor google__cloud__dialogflow__v2beta1__knowledge_bases__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_google_2fcloud_2fdialogflow_2fv2beta1_2fknowledge_5fbase_2eproto__INCLUDED */
