/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/longrunning/operations.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "operations.pb-c.h"
void   google__longrunning__operation__init
                     (Google__Longrunning__Operation         *message)
{
  static const Google__Longrunning__Operation init_value = GOOGLE__LONGRUNNING__OPERATION__INIT;
  *message = init_value;
}
size_t google__longrunning__operation__get_packed_size
                     (const Google__Longrunning__Operation *message)
{
  assert(message->base.descriptor == &google__longrunning__operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__operation__pack
                     (const Google__Longrunning__Operation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__operation__pack_to_buffer
                     (const Google__Longrunning__Operation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__Operation *
       google__longrunning__operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__Operation *)
     protobuf_c_message_unpack (&google__longrunning__operation__descriptor,
                                allocator, len, data);
}
void   google__longrunning__operation__free_unpacked
                     (Google__Longrunning__Operation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__longrunning__get_operation_request__init
                     (Google__Longrunning__GetOperationRequest         *message)
{
  static const Google__Longrunning__GetOperationRequest init_value = GOOGLE__LONGRUNNING__GET_OPERATION_REQUEST__INIT;
  *message = init_value;
}
size_t google__longrunning__get_operation_request__get_packed_size
                     (const Google__Longrunning__GetOperationRequest *message)
{
  assert(message->base.descriptor == &google__longrunning__get_operation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__get_operation_request__pack
                     (const Google__Longrunning__GetOperationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__get_operation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__get_operation_request__pack_to_buffer
                     (const Google__Longrunning__GetOperationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__get_operation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__GetOperationRequest *
       google__longrunning__get_operation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__GetOperationRequest *)
     protobuf_c_message_unpack (&google__longrunning__get_operation_request__descriptor,
                                allocator, len, data);
}
void   google__longrunning__get_operation_request__free_unpacked
                     (Google__Longrunning__GetOperationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__get_operation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__longrunning__list_operations_request__init
                     (Google__Longrunning__ListOperationsRequest         *message)
{
  static const Google__Longrunning__ListOperationsRequest init_value = GOOGLE__LONGRUNNING__LIST_OPERATIONS_REQUEST__INIT;
  *message = init_value;
}
size_t google__longrunning__list_operations_request__get_packed_size
                     (const Google__Longrunning__ListOperationsRequest *message)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__list_operations_request__pack
                     (const Google__Longrunning__ListOperationsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__list_operations_request__pack_to_buffer
                     (const Google__Longrunning__ListOperationsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__ListOperationsRequest *
       google__longrunning__list_operations_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__ListOperationsRequest *)
     protobuf_c_message_unpack (&google__longrunning__list_operations_request__descriptor,
                                allocator, len, data);
}
void   google__longrunning__list_operations_request__free_unpacked
                     (Google__Longrunning__ListOperationsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__list_operations_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__longrunning__list_operations_response__init
                     (Google__Longrunning__ListOperationsResponse         *message)
{
  static const Google__Longrunning__ListOperationsResponse init_value = GOOGLE__LONGRUNNING__LIST_OPERATIONS_RESPONSE__INIT;
  *message = init_value;
}
size_t google__longrunning__list_operations_response__get_packed_size
                     (const Google__Longrunning__ListOperationsResponse *message)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__list_operations_response__pack
                     (const Google__Longrunning__ListOperationsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__list_operations_response__pack_to_buffer
                     (const Google__Longrunning__ListOperationsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__list_operations_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__ListOperationsResponse *
       google__longrunning__list_operations_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__ListOperationsResponse *)
     protobuf_c_message_unpack (&google__longrunning__list_operations_response__descriptor,
                                allocator, len, data);
}
void   google__longrunning__list_operations_response__free_unpacked
                     (Google__Longrunning__ListOperationsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__list_operations_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__longrunning__cancel_operation_request__init
                     (Google__Longrunning__CancelOperationRequest         *message)
{
  static const Google__Longrunning__CancelOperationRequest init_value = GOOGLE__LONGRUNNING__CANCEL_OPERATION_REQUEST__INIT;
  *message = init_value;
}
size_t google__longrunning__cancel_operation_request__get_packed_size
                     (const Google__Longrunning__CancelOperationRequest *message)
{
  assert(message->base.descriptor == &google__longrunning__cancel_operation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__cancel_operation_request__pack
                     (const Google__Longrunning__CancelOperationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__cancel_operation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__cancel_operation_request__pack_to_buffer
                     (const Google__Longrunning__CancelOperationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__cancel_operation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__CancelOperationRequest *
       google__longrunning__cancel_operation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__CancelOperationRequest *)
     protobuf_c_message_unpack (&google__longrunning__cancel_operation_request__descriptor,
                                allocator, len, data);
}
void   google__longrunning__cancel_operation_request__free_unpacked
                     (Google__Longrunning__CancelOperationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__cancel_operation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__longrunning__delete_operation_request__init
                     (Google__Longrunning__DeleteOperationRequest         *message)
{
  static const Google__Longrunning__DeleteOperationRequest init_value = GOOGLE__LONGRUNNING__DELETE_OPERATION_REQUEST__INIT;
  *message = init_value;
}
size_t google__longrunning__delete_operation_request__get_packed_size
                     (const Google__Longrunning__DeleteOperationRequest *message)
{
  assert(message->base.descriptor == &google__longrunning__delete_operation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__longrunning__delete_operation_request__pack
                     (const Google__Longrunning__DeleteOperationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__longrunning__delete_operation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__longrunning__delete_operation_request__pack_to_buffer
                     (const Google__Longrunning__DeleteOperationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__longrunning__delete_operation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Longrunning__DeleteOperationRequest *
       google__longrunning__delete_operation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Longrunning__DeleteOperationRequest *)
     protobuf_c_message_unpack (&google__longrunning__delete_operation_request__descriptor,
                                allocator, len, data);
}
void   google__longrunning__delete_operation_request__free_unpacked
                     (Google__Longrunning__DeleteOperationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__longrunning__delete_operation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor google__longrunning__operation__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__Operation, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__Operation, metadata),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__Operation, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Longrunning__Operation, result_case),
    offsetof(Google__Longrunning__Operation, error),
    &google__rpc__status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Longrunning__Operation, result_case),
    offsetof(Google__Longrunning__Operation, response),
    &google__protobuf__any__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__operation__field_indices_by_name[] = {
  2,   /* field[2] = done */
  3,   /* field[3] = error */
  1,   /* field[1] = metadata */
  0,   /* field[0] = name */
  4,   /* field[4] = response */
};
static const ProtobufCIntRange google__longrunning__operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor google__longrunning__operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.Operation",
  "Operation",
  "Google__Longrunning__Operation",
  "google.longrunning",
  sizeof(Google__Longrunning__Operation),
  5,
  google__longrunning__operation__field_descriptors,
  google__longrunning__operation__field_indices_by_name,
  1,  google__longrunning__operation__number_ranges,
  (ProtobufCMessageInit) google__longrunning__operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__longrunning__get_operation_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__GetOperationRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__get_operation_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__longrunning__get_operation_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__longrunning__get_operation_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.GetOperationRequest",
  "GetOperationRequest",
  "Google__Longrunning__GetOperationRequest",
  "google.longrunning",
  sizeof(Google__Longrunning__GetOperationRequest),
  1,
  google__longrunning__get_operation_request__field_descriptors,
  google__longrunning__get_operation_request__field_indices_by_name,
  1,  google__longrunning__get_operation_request__number_ranges,
  (ProtobufCMessageInit) google__longrunning__get_operation_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__longrunning__list_operations_request__field_descriptors[4] =
{
  {
    "filter",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__ListOperationsRequest, filter),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__ListOperationsRequest, page_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_token",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__ListOperationsRequest, page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__ListOperationsRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__list_operations_request__field_indices_by_name[] = {
  0,   /* field[0] = filter */
  3,   /* field[3] = name */
  1,   /* field[1] = page_size */
  2,   /* field[2] = page_token */
};
static const ProtobufCIntRange google__longrunning__list_operations_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor google__longrunning__list_operations_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.ListOperationsRequest",
  "ListOperationsRequest",
  "Google__Longrunning__ListOperationsRequest",
  "google.longrunning",
  sizeof(Google__Longrunning__ListOperationsRequest),
  4,
  google__longrunning__list_operations_request__field_descriptors,
  google__longrunning__list_operations_request__field_indices_by_name,
  1,  google__longrunning__list_operations_request__number_ranges,
  (ProtobufCMessageInit) google__longrunning__list_operations_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__longrunning__list_operations_response__field_descriptors[2] =
{
  {
    "operations",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Longrunning__ListOperationsResponse, n_operations),
    offsetof(Google__Longrunning__ListOperationsResponse, operations),
    &google__longrunning__operation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_page_token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__ListOperationsResponse, next_page_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__list_operations_response__field_indices_by_name[] = {
  1,   /* field[1] = next_page_token */
  0,   /* field[0] = operations */
};
static const ProtobufCIntRange google__longrunning__list_operations_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor google__longrunning__list_operations_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.ListOperationsResponse",
  "ListOperationsResponse",
  "Google__Longrunning__ListOperationsResponse",
  "google.longrunning",
  sizeof(Google__Longrunning__ListOperationsResponse),
  2,
  google__longrunning__list_operations_response__field_descriptors,
  google__longrunning__list_operations_response__field_indices_by_name,
  1,  google__longrunning__list_operations_response__number_ranges,
  (ProtobufCMessageInit) google__longrunning__list_operations_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__longrunning__cancel_operation_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__CancelOperationRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__cancel_operation_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__longrunning__cancel_operation_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__longrunning__cancel_operation_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.CancelOperationRequest",
  "CancelOperationRequest",
  "Google__Longrunning__CancelOperationRequest",
  "google.longrunning",
  sizeof(Google__Longrunning__CancelOperationRequest),
  1,
  google__longrunning__cancel_operation_request__field_descriptors,
  google__longrunning__cancel_operation_request__field_indices_by_name,
  1,  google__longrunning__cancel_operation_request__number_ranges,
  (ProtobufCMessageInit) google__longrunning__cancel_operation_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__longrunning__delete_operation_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Longrunning__DeleteOperationRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__longrunning__delete_operation_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange google__longrunning__delete_operation_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor google__longrunning__delete_operation_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.longrunning.DeleteOperationRequest",
  "DeleteOperationRequest",
  "Google__Longrunning__DeleteOperationRequest",
  "google.longrunning",
  sizeof(Google__Longrunning__DeleteOperationRequest),
  1,
  google__longrunning__delete_operation_request__field_descriptors,
  google__longrunning__delete_operation_request__field_indices_by_name,
  1,  google__longrunning__delete_operation_request__number_ranges,
  (ProtobufCMessageInit) google__longrunning__delete_operation_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor google__longrunning__operations__method_descriptors[4] =
{
  { "ListOperations", &google__longrunning__list_operations_request__descriptor, &google__longrunning__list_operations_response__descriptor },
  { "GetOperation", &google__longrunning__get_operation_request__descriptor, &google__longrunning__operation__descriptor },
  { "DeleteOperation", &google__longrunning__delete_operation_request__descriptor, &google__protobuf__empty__descriptor },
  { "CancelOperation", &google__longrunning__cancel_operation_request__descriptor, &google__protobuf__empty__descriptor },
};
const unsigned google__longrunning__operations__method_indices_by_name[] = {
  3,        /* CancelOperation */
  2,        /* DeleteOperation */
  1,        /* GetOperation */
  0         /* ListOperations */
};
const ProtobufCServiceDescriptor google__longrunning__operations__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "google.longrunning.Operations",
  "Operations",
  "Google__Longrunning__Operations",
  "google.longrunning",
  4,
  google__longrunning__operations__method_descriptors,
  google__longrunning__operations__method_indices_by_name
};
void google__longrunning__operations__list_operations(ProtobufCService *service,
                                                      const Google__Longrunning__ListOperationsRequest *input,
                                                      Google__Longrunning__ListOperationsResponse_Closure closure,
                                                      void *closure_data)
{
  assert(service->descriptor == &google__longrunning__operations__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__longrunning__operations__get_operation(ProtobufCService *service,
                                                    const Google__Longrunning__GetOperationRequest *input,
                                                    Google__Longrunning__Operation_Closure closure,
                                                    void *closure_data)
{
  assert(service->descriptor == &google__longrunning__operations__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__longrunning__operations__delete_operation(ProtobufCService *service,
                                                       const Google__Longrunning__DeleteOperationRequest *input,
                                                       Google__Protobuf__Empty_Closure closure,
                                                       void *closure_data)
{
  assert(service->descriptor == &google__longrunning__operations__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__longrunning__operations__cancel_operation(ProtobufCService *service,
                                                       const Google__Longrunning__CancelOperationRequest *input,
                                                       Google__Protobuf__Empty_Closure closure,
                                                       void *closure_data)
{
  assert(service->descriptor == &google__longrunning__operations__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void google__longrunning__operations__init (Google__Longrunning__Operations_Service *service,
                                            Google__Longrunning__Operations_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &google__longrunning__operations__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
