/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: google/cloud/dialogflow/v2beta1/webhook.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "webhook.pb-c.h"
void   google__cloud__dialogflow__v2beta1__webhook_request__init
                     (Google__Cloud__Dialogflow__V2beta1__WebhookRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__WebhookRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__WEBHOOK_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__webhook_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__webhook_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__webhook_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__WebhookRequest *
       google__cloud__dialogflow__v2beta1__webhook_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__WebhookRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__webhook_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__webhook_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__WebhookRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__webhook_response__init
                     (Google__Cloud__Dialogflow__V2beta1__WebhookResponse         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__WebhookResponse init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__WEBHOOK_RESPONSE__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__webhook_response__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookResponse *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__webhook_response__pack
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__webhook_response__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__WebhookResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__WebhookResponse *
       google__cloud__dialogflow__v2beta1__webhook_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__WebhookResponse *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__webhook_response__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__webhook_response__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__WebhookResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__webhook_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   google__cloud__dialogflow__v2beta1__original_detect_intent_request__init
                     (Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest         *message)
{
  static const Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest init_value = GOOGLE__CLOUD__DIALOGFLOW__V2BETA1__ORIGINAL_DETECT_INTENT_REQUEST__INIT;
  *message = init_value;
}
size_t google__cloud__dialogflow__v2beta1__original_detect_intent_request__get_packed_size
                     (const Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *message)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__cloud__dialogflow__v2beta1__original_detect_intent_request__pack
                     (const Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__cloud__dialogflow__v2beta1__original_detect_intent_request__pack_to_buffer
                     (const Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *
       google__cloud__dialogflow__v2beta1__original_detect_intent_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *)
     protobuf_c_message_unpack (&google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor,
                                allocator, len, data);
}
void   google__cloud__dialogflow__v2beta1__original_detect_intent_request__free_unpacked
                     (Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__webhook_request__field_descriptors[5] =
{
  {
    "response_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, response_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query_result",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, query_result),
    &google__cloud__dialogflow__v2beta1__query_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original_detect_intent_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, original_detect_intent_request),
    &google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, session),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alternative_query_results",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, n_alternative_query_results),
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest, alternative_query_results),
    &google__cloud__dialogflow__v2beta1__query_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__webhook_request__field_indices_by_name[] = {
  4,   /* field[4] = alternative_query_results */
  2,   /* field[2] = original_detect_intent_request */
  1,   /* field[1] = query_result */
  0,   /* field[0] = response_id */
  3,   /* field[3] = session */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__webhook_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__webhook_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.WebhookRequest",
  "WebhookRequest",
  "Google__Cloud__Dialogflow__V2beta1__WebhookRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__WebhookRequest),
  5,
  google__cloud__dialogflow__v2beta1__webhook_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__webhook_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__webhook_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__webhook_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__webhook_response__field_descriptors[7] =
{
  {
    "fulfillment_text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, fulfillment_text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fulfillment_messages",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, n_fulfillment_messages),
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, fulfillment_messages),
    &google__cloud__dialogflow__v2beta1__intent__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, payload),
    &google__protobuf__struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_contexts",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, n_output_contexts),
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, output_contexts),
    &google__cloud__dialogflow__v2beta1__context__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "followup_event_input",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, followup_event_input),
    &google__cloud__dialogflow__v2beta1__event_input__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_interaction",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse, end_interaction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__webhook_response__field_indices_by_name[] = {
  6,   /* field[6] = end_interaction */
  5,   /* field[5] = followup_event_input */
  1,   /* field[1] = fulfillment_messages */
  0,   /* field[0] = fulfillment_text */
  4,   /* field[4] = output_contexts */
  3,   /* field[3] = payload */
  2,   /* field[2] = source */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__webhook_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__webhook_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.WebhookResponse",
  "WebhookResponse",
  "Google__Cloud__Dialogflow__V2beta1__WebhookResponse",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__WebhookResponse),
  7,
  google__cloud__dialogflow__v2beta1__webhook_response__field_descriptors,
  google__cloud__dialogflow__v2beta1__webhook_response__field_indices_by_name,
  2,  google__cloud__dialogflow__v2beta1__webhook_response__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__webhook_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor google__cloud__dialogflow__v2beta1__original_detect_intent_request__field_descriptors[3] =
{
  {
    "source",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest, payload),
    &google__protobuf__struct__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned google__cloud__dialogflow__v2beta1__original_detect_intent_request__field_indices_by_name[] = {
  2,   /* field[2] = payload */
  0,   /* field[0] = source */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange google__cloud__dialogflow__v2beta1__original_detect_intent_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor google__cloud__dialogflow__v2beta1__original_detect_intent_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.cloud.dialogflow.v2beta1.OriginalDetectIntentRequest",
  "OriginalDetectIntentRequest",
  "Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest",
  "google.cloud.dialogflow.v2beta1",
  sizeof(Google__Cloud__Dialogflow__V2beta1__OriginalDetectIntentRequest),
  3,
  google__cloud__dialogflow__v2beta1__original_detect_intent_request__field_descriptors,
  google__cloud__dialogflow__v2beta1__original_detect_intent_request__field_indices_by_name,
  1,  google__cloud__dialogflow__v2beta1__original_detect_intent_request__number_ranges,
  (ProtobufCMessageInit) google__cloud__dialogflow__v2beta1__original_detect_intent_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
