COMPONENT_ADD_INCLUDEDIRS :=  include

ESP_DOWNMIX_LIB_PATH := $(COMPONENT_PATH)/lib/libesp-downmix.a
COMPONENT_ADD_LDFLAGS += $(ESP_DOWNMIX_LIB_PATH)
COMPONENT_ADD_LINKER_DEPS += $(ESP_DOWNMIX_LIB_PATH)
