#
# Component Makefile
#

COMPONENT_ADD_INCLUDEDIRS := include


ifeq ("$(VOICE_ASSISTANT)","gva")
VOICE_ASSISTANT_LIB_PATH := $(COMPONENT_PATH)/lib/libgva.a
else ifeq ("$(VOICE_ASSISTANT)","dialogflow")
VOICE_ASSISTANT_LIB_PATH := $(COMPONENT_PATH)/lib/libdialogflow.a
else ifeq ("$(VOICE_ASSISTANT)","aia")
VOICE_ASSISTANT_LIB_PATH := $(COMPONENT_PATH)/lib/libaia.a
else ifeq ("$(VOICE_ASSISTANT)","avs")
VOICE_ASSISTANT_LIB_PATH := $(COMPONENT_PATH)/lib/libavs.a
endif

COMPONENT_ADD_LDFLAGS += $(VOICE_ASSISTANT_LIB_PATH)
COMPONENT_ADD_LINKER_DEPS += $(VOICE_ASSISTANT_LIB_PATH)
