#
# Component Makefile
#

COMPONENT_ADD_INCLUDEDIRS := include/

CODEC_ZL38063_LIB_PATH := $(COMPONENT_PATH)/lib/libfirmware_zl38063.a
COMPONENT_ADD_LDFLAGS += $(CODEC_ZL38063_LIB_PATH)
COMPONENT_ADD_LINKER_DEPS += $(CODEC_ZL38063_LIB_PATH)
